services:
  backend:
    image: ghcr.io/patryk-bernasiewicz/gjk-backend:180525_1510
    ports:
      - target: 3220
        published: 3220
        protocol: tcp
        mode: host
    environment:
      NODE_ENV: development
      PORT: 3220
    secrets:
      - GJK_DEV_DATABASE_URL
      - GJK_DEV_CLERK_SECRET_KEY
    entrypoint:
      - sh
      - -c
      - |
        export DATABASE_URL=$$(cat /run/secrets/GJK_DEV_DATABASE_URL) && \
        export CLERK_SECRET_KEY=$$(cat /run/secrets/GJK_DEV_CLERK_SECRET_KEY) && \
        npm run start:prod
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://127.0.0.1:3220/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

secrets:
  GJK_DEV_CLERK_SECRET_KEY:
    external: true
  GJK_DEV_DATABASE_URL:
    external: true
